#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    wp-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^wp\.ddev\.site$`)
      
      service: "wp-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "wp-redirectHttps"
    wp-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^wp\.ddev\.site$`)
      
      service: "wp-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "wp-redirectHttps"
    wp-elasticsearch-9200-http:
      entrypoints:
        - http-9200
      rule: HostRegexp(`^wp\.ddev\.site$`)
      
      service: "wp-elasticsearch-9200"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "wp-redirectHttps"
    
    
    
    wp-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^wp\.ddev\.site$`)
      
      service: "wp-web-80"
      ruleSyntax: v3
      
      tls: true
      
    wp-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^wp\.ddev\.site$`)
      
      service: "wp-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    
    wp-elasticsearch-9200-https:
      entrypoints:
        - http-9201
      rule: HostRegexp(`^wp\.ddev\.site$`)
      
      service: "wp-elasticsearch-9200"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    wp-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    wp-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-wp-web:80
        
    wp-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-wp-web:8025
        
    
    
    wp-elasticsearch-9200:
      loadbalancer:
        servers:
          - url: http://ddev-wp-elasticsearch:9200
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/wp.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/wp.key